/**
 * Generates the launcher icon's vector path from Bravura itself.
 *
 * The app's icon is a treble clef, and the one authoritative treble clef in this repo is the glyph
 * in the font the staff is already drawn with. Tracing one by hand would produce a second, slightly
 * different clef — the same duplication the twin laws forbid, just in vector form. So the outline is
 * extracted from the shipped font and emitted as Android `pathData`.
 *
 * Run with (JDK 21 single-file source mode, no build wiring needed):
 *   java tools/icon/GenerateIcon.java
 *
 * It rewrites app/src/main/res/drawable/ic_launcher_foreground.xml and ic_launcher_monochrome.xml.
 * Re-run it if the font version changes; otherwise the committed output is what ships.
 */
import java.awt.Font;
import java.awt.font.FontRenderContext;
import java.awt.font.GlyphVector;
import java.awt.geom.AffineTransform;
import java.awt.geom.PathIterator;
import java.awt.geom.Rectangle2D;
import java.io.File;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Locale;

public final class GenerateIcon {

    /** SMuFL codepoint for gClef. Not looked up from glyphnames.json to keep this a zero-dep tool. */
    private static final int G_CLEF = 0xE050;

    /** Adaptive icons are 108x108dp with only the central ~66dp guaranteed visible. */
    private static final double CANVAS = 108;
    private static final double SAFE_HEIGHT = 74;

    public static void main(String[] args) throws Exception {
        Path repo = Path.of(".").toAbsolutePath().normalize();
        File fontFile = repo.resolve("app/src/main/res/font/bravura.otf").toFile();
        if (!fontFile.exists()) {
            System.err.println("run this from the repo root; not found: " + fontFile);
            System.exit(1);
        }

        Font bravura = Font.createFont(Font.TRUETYPE_FONT, fontFile).deriveFont(100f);
        FontRenderContext frc = new FontRenderContext(null, true, true);
        GlyphVector gv = bravura.createGlyphVector(frc, new String(Character.toChars(G_CLEF)));
        var outline = gv.getOutline();
        Rectangle2D bounds = outline.getBounds2D();

        // Scale to the safe height, then centre on the canvas.
        double scale = SAFE_HEIGHT / bounds.getHeight();
        AffineTransform fit = new AffineTransform();
        fit.translate(
                (CANVAS - bounds.getWidth() * scale) / 2 - bounds.getX() * scale,
                (CANVAS - bounds.getHeight() * scale) / 2 - bounds.getY() * scale);
        fit.scale(scale, scale);

        String pathData = toPathData(outline.getPathIterator(fit));
        System.out.printf("glyph bounds %.1fx%.1f, scale %.3f, %d chars of path data%n",
                bounds.getWidth(), bounds.getHeight(), scale, pathData.length());

        write(repo.resolve("app/src/main/res/drawable/ic_launcher_foreground.xml"), pathData, "#E8A13C");
        write(repo.resolve("app/src/main/res/drawable/ic_launcher_monochrome.xml"), pathData, "#FFFFFF");
    }

    private static void write(Path target, String pathData, String colour) throws Exception {
        String xml = """
                <?xml version="1.0" encoding="utf-8"?>
                <!-- Generated by tools/icon/GenerateIcon.java from Bravura's gClef. Do not hand-edit. -->
                <vector xmlns:android="http://schemas.android.com/apk/res/android"
                    android:width="108dp"
                    android:height="108dp"
                    android:viewportWidth="108"
                    android:viewportHeight="108">
                    <path
                        android:fillColor="%s"
                        android:fillType="nonZero"
                        android:pathData="%s" />
                </vector>
                """.formatted(colour, pathData);
        Files.writeString(target, xml);
        System.out.println("wrote " + target);
    }

    private static String toPathData(PathIterator it) {
        StringBuilder out = new StringBuilder();
        double[] c = new double[6];
        while (!it.isDone()) {
            switch (it.currentSegment(c)) {
                case PathIterator.SEG_MOVETO -> out.append("M").append(n(c[0])).append(",").append(n(c[1]));
                case PathIterator.SEG_LINETO -> out.append("L").append(n(c[0])).append(",").append(n(c[1]));
                case PathIterator.SEG_QUADTO -> out.append("Q").append(n(c[0])).append(",").append(n(c[1]))
                        .append(" ").append(n(c[2])).append(",").append(n(c[3]));
                case PathIterator.SEG_CUBICTO -> out.append("C").append(n(c[0])).append(",").append(n(c[1]))
                        .append(" ").append(n(c[2])).append(",").append(n(c[3]))
                        .append(" ").append(n(c[4])).append(",").append(n(c[5]));
                case PathIterator.SEG_CLOSE -> out.append("Z");
                default -> throw new IllegalStateException("unknown path segment");
            }
            out.append(" ");
            it.next();
        }
        return out.toString().trim();
    }

    /** Two decimals: the canvas is 108 units, so more precision is bytes with no visible effect. */
    private static String n(double value) {
        return String.format(Locale.ROOT, "%.2f", value);
    }
}
